/**
 * Collects sync job dispatch metadata from each plugin's `src/sync-registry.ts`
 * and generates `dispatch-registry.gen.ts` for the plugin-sync-dispatch Edge function.
 *
 * Run via `tsx` from the repo root (see `sync-plugins.mjs`).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");
const pluginsRoot = path.join(repoRoot, "packages", "plugins");

const registryOutPath = path.join(
  repoRoot,
  "packages",
  "supabase",
  "supabase",
  "functions",
  "plugin-sync-dispatch",
  "dispatch-registry.gen.ts",
);

type SyncRegistryEntry = {
  pluginTypeId: string;
  dispatchFunctionSlug: string;
};

async function collectFromPlugins(): Promise<SyncRegistryEntry[]> {
  const entries: SyncRegistryEntry[] = [];

  for (const ent of fs.readdirSync(pluginsRoot, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    const syncRegistryTs = path.join(
      pluginsRoot,
      ent.name,
      "src",
      "sync-registry.ts",
    );
    if (!fs.existsSync(syncRegistryTs)) continue;

    let mod: Record<string, unknown>;
    try {
      mod = await import(pathToFileURL(syncRegistryTs).href);
    } catch {
      console.warn(
        `extract-plugin-sync-registry: skipping ${path.relative(repoRoot, syncRegistryTs)} (import failed)`,
      );
      continue;
    }

    for (const value of Object.values(mod)) {
      if (!value || typeof value !== "object") continue;
      const o = value as Record<string, unknown>;
      const pluginTypeId = o.pluginTypeId;
      const dispatchFunctionSlug = o.dispatchFunctionSlug;
      if (
        typeof pluginTypeId !== "string" ||
        !pluginTypeId.trim() ||
        typeof dispatchFunctionSlug !== "string" ||
        !dispatchFunctionSlug.trim()
      ) {
        continue;
      }
      entries.push({
        pluginTypeId: pluginTypeId.trim(),
        dispatchFunctionSlug: dispatchFunctionSlug.trim(),
      });
    }
  }

  entries.sort((a, b) => a.pluginTypeId.localeCompare(b.pluginTypeId));
  return entries;
}

function emitRegistry(entries: SyncRegistryEntry[]): void {
  const lines = [
    `/** @generated by packages/supabase/scripts/extract-plugin-sync-registry.ts — do not edit */`,
    ``,
    `export type PluginSyncDispatchRegistryEntry = {`,
    `  pluginTypeId: string;`,
    `  dispatchFunctionSlug: string;`,
    `};`,
    ``,
    `export const PLUGIN_SYNC_DISPATCH_REGISTRY: readonly PluginSyncDispatchRegistryEntry[] = [`,
  ];

  for (const entry of entries) {
    lines.push(`  {`);
    lines.push(`    pluginTypeId: ${JSON.stringify(entry.pluginTypeId)},`);
    lines.push(
      `    dispatchFunctionSlug: ${JSON.stringify(entry.dispatchFunctionSlug)},`,
    );
    lines.push(`  },`);
  }

  lines.push(`];`, ``);

  fs.mkdirSync(path.dirname(registryOutPath), { recursive: true });
  fs.writeFileSync(registryOutPath, lines.join("\n") + "\n", "utf8");

  console.log(
    `extract-plugin-sync-registry: wrote ${path.relative(repoRoot, registryOutPath)} (${entries.length} plugin(s))`,
  );
}

async function main(): Promise<void> {
  emitRegistry(await collectFromPlugins());
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
