/** @generated by packages/supabase/scripts/extract-plugin-sync-registry.ts — do not edit */

export type PluginSyncDispatchRegistryEntry = {
  pluginTypeId: string;
  dispatchFunctionSlug: string;
};

export const PLUGIN_SYNC_DISPATCH_REGISTRY: readonly PluginSyncDispatchRegistryEntry[] =
  [
    {
      pluginTypeId: "osm-poi",
      dispatchFunctionSlug: "osm-poi-dispatch",
    },
  ];
