/** Exact phrase → emoji matches (normalized lowercase keys). */
export const PHRASE_EMOJI: Readonly<Record<string, string>> = {
  "starred places": "⭐",
  starred: "⭐",
  favorites: "❤️",
  favourite: "❤️",
  favourites: "❤️",
  "want to go": "📌",
  "want to visit": "📌",
  bucket: "🪣",
  "bucket list": "📝",
  restaurants: "🍽️",
  restaurant: "🍽️",
  food: "🍽️",
  dining: "🍽️",
  cafes: "☕",
  cafe: "☕",
  coffee: "☕",
  bars: "🍺",
  bar: "🍺",
  nightlife: "🌃",
  hotels: "🏨",
  hotel: "🏨",
  accommodation: "🏨",
  lodging: "🏨",
  beaches: "🏖️",
  beach: "🏖️",
  swimming: "🏊",
  hiking: "🥾",
  trails: "🥾",
  trail: "🥾",
  camping: "🏕️",
  camp: "⛺",
  parks: "🌳",
  park: "🌳",
  nature: "🌿",
  museums: "🏛️",
  museum: "🏛️",
  art: "🎨",
  gallery: "🖼️",
  shopping: "🛍️",
  shops: "🛍️",
  market: "🛒",
  groceries: "🛒",
  grocery: "🛒",
  bakery: "🥐",
  pizza: "🍕",
  sushi: "🍣",
  ramen: "🍜",
  tacos: "🌮",
  burgers: "🍔",
  wine: "🍷",
  brewery: "🍺",
  gym: "💪",
  fitness: "💪",
  yoga: "🧘",
  spa: "💆",
  airport: "✈️",
  flights: "✈️",
  travel: "✈️",
  vacation: "🏖️",
  holiday: "🏖️",
  trip: "🧳",
  trips: "🧳",
  family: "👨‍👩‍👧‍👦",
  kids: "👶",
  wedding: "💒",
  date: "💕",
  dates: "💕",
  work: "💼",
  office: "🏢",
  home: "🏠",
  church: "⛪",
  temple: "🛕",
  mosque: "🕌",
  synagogue: "🕍",
  hospital: "🏥",
  doctor: "🩺",
  pharmacy: "💊",
  school: "🏫",
  university: "🎓",
  library: "📚",
  books: "📚",
  music: "🎵",
  concert: "🎤",
  sports: "⚽",
  soccer: "⚽",
  football: "🏈",
  basketball: "🏀",
  tennis: "🎾",
  golf: "⛳",
  ski: "⛷️",
  skiing: "⛷️",
  snowboard: "🏂",
  surf: "🏄",
  surfing: "🏄",
  dive: "🤿",
  diving: "🤿",
  zoo: "🦁",
  aquarium: "🐠",
  garden: "🌷",
  flowers: "💐",
  farm: "🚜",
  vineyard: "🍇",
  christmas: "🎄",
  halloween: "🎃",
  birthday: "🎂",
  party: "🎉",
  picnic: "🧺",
  bbq: "🍖",
  barbecue: "🍖",
  brunch: "🥞",
  breakfast: "🥞",
  dessert: "🍰",
  ice: "🍦",
  icecream: "🍦",
  vegan: "🥗",
  vegetarian: "🥗",
  asia: "🌏",
  europe: "🇪🇺",
  paris: "🗼",
  london: "🇬🇧",
  tokyo: "🗼",
  "new york": "🗽",
  nyc: "🗽",
  "san francisco": "🌉",
  la: "🌴",
  "los angeles": "🌴",
};

/** Single-token keyword → emoji for token scoring. */
export const KEYWORD_EMOJI: Readonly<Record<string, string>> = {
  star: "⭐",
  starred: "⭐",
  favorite: "❤️",
  fav: "❤️",
  love: "❤️",
  heart: "❤️",
  food: "🍽️",
  eat: "🍽️",
  restaurant: "🍽️",
  dining: "🍽️",
  cafe: "☕",
  coffee: "☕",
  tea: "🍵",
  bar: "🍺",
  pub: "🍺",
  drink: "🍹",
  cocktail: "🍸",
  wine: "🍷",
  beer: "🍺",
  hotel: "🏨",
  hostel: "🏨",
  motel: "🏨",
  stay: "🏨",
  sleep: "😴",
  beach: "🏖️",
  ocean: "🌊",
  sea: "🌊",
  lake: "🏞️",
  river: "🏞️",
  mountain: "⛰️",
  mountains: "⛰️",
  hike: "🥾",
  hiking: "🥾",
  trail: "🥾",
  camp: "⛺",
  camping: "🏕️",
  park: "🌳",
  forest: "🌲",
  garden: "🌷",
  nature: "🌿",
  wildlife: "🦁",
  zoo: "🦁",
  museum: "🏛️",
  art: "🎨",
  gallery: "🖼️",
  shop: "🛍️",
  shopping: "🛍️",
  store: "🏪",
  market: "🛒",
  grocery: "🛒",
  bakery: "🥐",
  pizza: "🍕",
  sushi: "🍣",
  ramen: "🍜",
  taco: "🌮",
  burger: "🍔",
  brunch: "🥞",
  breakfast: "🥞",
  lunch: "🍱",
  dinner: "🍽️",
  dessert: "🍰",
  cake: "🎂",
  gym: "💪",
  fitness: "💪",
  yoga: "🧘",
  spa: "💆",
  pool: "🏊",
  swim: "🏊",
  surf: "🏄",
  ski: "⛷️",
  snowboard: "🏂",
  golf: "⛳",
  tennis: "🎾",
  soccer: "⚽",
  football: "🏈",
  basketball: "🏀",
  sport: "⚽",
  sports: "⚽",
  airport: "✈️",
  flight: "✈️",
  fly: "✈️",
  travel: "✈️",
  trip: "🧳",
  vacation: "🏖️",
  holiday: "🏖️",
  family: "👨‍👩‍👧‍👦",
  kid: "👶",
  kids: "👶",
  baby: "👶",
  wedding: "💒",
  date: "💕",
  work: "💼",
  office: "🏢",
  home: "🏠",
  house: "🏠",
  church: "⛪",
  temple: "🛕",
  hospital: "🏥",
  doctor: "🩺",
  school: "🏫",
  university: "🎓",
  college: "🎓",
  library: "📚",
  book: "📚",
  music: "🎵",
  concert: "🎤",
  party: "🎉",
  picnic: "🧺",
  bbq: "🍖",
  vegan: "🥗",
  salad: "🥗",
  asia: "🌏",
  europe: "🇪🇺",
  paris: "🗼",
  london: "🇬🇧",
  tokyo: "🗼",
  nyc: "🗽",
  christmas: "🎄",
  halloween: "🎃",
  birthday: "🎂",
  list: "📋",
  places: "📍",
  map: "🗺️",
  maps: "🗺️",
};

export const EMOJI_STOPWORDS = new Set([
  "a",
  "an",
  "the",
  "my",
  "our",
  "your",
  "and",
  "or",
  "of",
  "in",
  "on",
  "at",
  "to",
  "for",
  "from",
  "with",
  "by",
  "list",
  "lists",
  "place",
  "places",
  "spot",
  "spots",
  "location",
  "locations",
  "map",
  "maps",
  "saved",
  "collection",
  "collections",
]);
